apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: antidote-setup
  labels:
    app: antidote
spec:
  serviceName: antidote-setup
  replicas: 1
  template:
    metadata:
      labels:
        app: antidote
    spec:
      containers:
        - image: erlang:19
          name: antidote-setup
          command: ["/bin/sh"]
          args: ["-c", "git clone https://github.com/deepthidevaki/antidote-aws; cd antidote-aws; code/link.sh 2 2"]
          volumeMounts:
          - name: host-mount
            mountPath: /code
      volumes:
      - name: host-mount
        hostPath:
          path: /home/docker/code/
